[project]
name = "eth-account-abstraction"
version = "0.0.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
fuels = { version = "0.25", features = ["fuel-core-lib"] }

[[test]]
harness = true
name = "integration_tests"
path = "tests/harness.rs"

[dependencies.async-std]
version = "1.6"
features = ["attributes"]