[project]
authors = ["Kyran Rawlinson"]
entry = "main.sw"
license = "Apache-2.0"
name = "eth-account-abstraction"

[dependencies]

[constants]
#An example public key, derived from the example private key:
#
#config_spender = { type = "B512", value = "" }
