[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "oracle"

[constants]
# Change to an Identity once https://github.com/FuelLabs/sway/issues/2647 is fixed
owner = { type = "b256", value = "0x94ffcc53b892684acefaebc8a3d4a595e528a8cf664eeb3ef36f1020b0809d0d" }

[dependencies]
