[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
license = "Apache-2.0"
name = "utils"
version = "0.0.0"

[dependencies]
fuels = { version = "0.31.1", features = ["fuel-core-lib"] }

[lib]
test = false
doctest = false
