/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.35.0
  Forc version: 0.35.3
  Fuel-Core version: 0.17.3
*/

import { Interface, Contract } from "fuels";
import type { Provider, Account, AbstractAddress } from "fuels";
import type {
  EscrowContractAbi,
  EscrowContractAbiInterface,
} from "../EscrowContractAbi";

const _abi = {
  types: [
    {
      typeId: 0,
      type: "()",
      components: [],
      typeParameters: null,
    },
    {
      typeId: 1,
      type: "b256",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 2,
      type: "bool",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 3,
      type: "enum ArbiterInputError",
      components: [
        {
          name: "AssetDoesNotMatch",
          type: 0,
          typeArguments: null,
        },
        {
          name: "CannotBeBuyer",
          type: 0,
          typeArguments: null,
        },
        {
          name: "CannotBeSeller",
          type: 0,
          typeArguments: null,
        },
        {
          name: "FeeCannotBeZero",
          type: 0,
          typeArguments: null,
        },
        {
          name: "FeeDoesNotMatchAmountSent",
          type: 0,
          typeArguments: null,
        },
        {
          name: "PaymentTooLarge",
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 4,
      type: "enum AssetInputError",
      components: [
        {
          name: "UnspecifiedAssets",
          type: 0,
          typeArguments: null,
        },
        {
          name: "AssetAmountCannotBeZero",
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 5,
      type: "enum DeadlineInputError",
      components: [
        {
          name: "MustBeInTheFuture",
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 6,
      type: "enum DepositError",
      components: [
        {
          name: "IncorrectAssetAmount",
          type: 0,
          typeArguments: null,
        },
        {
          name: "IncorrectAssetSent",
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 7,
      type: "enum Identity",
      components: [
        {
          name: "Address",
          type: 16,
          typeArguments: null,
        },
        {
          name: "ContractId",
          type: 20,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 8,
      type: "enum Option",
      components: [
        {
          name: "None",
          type: 0,
          typeArguments: null,
        },
        {
          name: "Some",
          type: 13,
          typeArguments: null,
        },
      ],
      typeParameters: [13],
    },
    {
      typeId: 9,
      type: "enum State",
      components: [
        {
          name: "Pending",
          type: 0,
          typeArguments: null,
        },
        {
          name: "Completed",
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 10,
      type: "enum StateError",
      components: [
        {
          name: "AlreadyDeposited",
          type: 0,
          typeArguments: null,
        },
        {
          name: "AlreadyDisputed",
          type: 0,
          typeArguments: null,
        },
        {
          name: "ArbiterHasNotBeenProposed",
          type: 0,
          typeArguments: null,
        },
        {
          name: "CannotDisputeBeforeDesposit",
          type: 0,
          typeArguments: null,
        },
        {
          name: "CannotResolveBeforeDesposit",
          type: 0,
          typeArguments: null,
        },
        {
          name: "CannotTakePaymentBeforeDeadline",
          type: 0,
          typeArguments: null,
        },
        {
          name: "CannotTakePaymentDuringDispute",
          type: 0,
          typeArguments: null,
        },
        {
          name: "CannotTransferBeforeDesposit",
          type: 0,
          typeArguments: null,
        },
        {
          name: "CannotWithdrawAfterDesposit",
          type: 0,
          typeArguments: null,
        },
        {
          name: "CannotWithdrawBeforeDeadline",
          type: 0,
          typeArguments: null,
        },
        {
          name: "EscrowExpired",
          type: 0,
          typeArguments: null,
        },
        {
          name: "NotDisputed",
          type: 0,
          typeArguments: null,
        },
        {
          name: "StateNotPending",
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 11,
      type: "enum UserError",
      components: [
        {
          name: "Unauthorized",
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 12,
      type: "enum UserInputError",
      components: [
        {
          name: "InvalidRecipient",
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 13,
      type: "generic T",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 14,
      type: "raw untyped ptr",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 15,
      type: "struct AcceptedArbiterEvent",
      components: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 16,
      type: "struct Address",
      components: [
        {
          name: "value",
          type: 1,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 17,
      type: "struct Arbiter",
      components: [
        {
          name: "address",
          type: 7,
          typeArguments: null,
        },
        {
          name: "asset",
          type: 20,
          typeArguments: null,
        },
        {
          name: "fee_amount",
          type: 34,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 18,
      type: "struct Asset",
      components: [
        {
          name: "amount",
          type: 34,
          typeArguments: null,
        },
        {
          name: "id",
          type: 20,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 19,
      type: "struct Buyer",
      components: [
        {
          name: "address",
          type: 7,
          typeArguments: null,
        },
        {
          name: "asset",
          type: 8,
          typeArguments: [
            {
              name: "",
              type: 20,
              typeArguments: null,
            },
          ],
        },
        {
          name: "deposited_amount",
          type: 34,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 20,
      type: "struct ContractId",
      components: [
        {
          name: "value",
          type: 1,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 21,
      type: "struct CreatedEscrowEvent",
      components: [
        {
          name: "escrow",
          type: 24,
          typeArguments: null,
        },
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 22,
      type: "struct DepositEvent",
      components: [
        {
          name: "asset",
          type: 20,
          typeArguments: null,
        },
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 23,
      type: "struct DisputeEvent",
      components: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 24,
      type: "struct EscrowInfo",
      components: [
        {
          name: "arbiter",
          type: 17,
          typeArguments: null,
        },
        {
          name: "asset_count",
          type: 34,
          typeArguments: null,
        },
        {
          name: "buyer",
          type: 19,
          typeArguments: null,
        },
        {
          name: "deadline",
          type: 34,
          typeArguments: null,
        },
        {
          name: "disputed",
          type: 2,
          typeArguments: null,
        },
        {
          name: "first_asset_index",
          type: 34,
          typeArguments: null,
        },
        {
          name: "seller",
          type: 30,
          typeArguments: null,
        },
        {
          name: "state",
          type: 9,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 25,
      type: "struct PaymentTakenEvent",
      components: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 26,
      type: "struct ProposedArbiterEvent",
      components: [
        {
          name: "arbiter",
          type: 17,
          typeArguments: null,
        },
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 27,
      type: "struct RawVec",
      components: [
        {
          name: "ptr",
          type: 14,
          typeArguments: null,
        },
        {
          name: "cap",
          type: 34,
          typeArguments: null,
        },
      ],
      typeParameters: [13],
    },
    {
      typeId: 28,
      type: "struct ResolvedDisputeEvent",
      components: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
        {
          name: "user",
          type: 7,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 29,
      type: "struct ReturnedDepositEvent",
      components: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 30,
      type: "struct Seller",
      components: [
        {
          name: "address",
          type: 7,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 31,
      type: "struct TransferredToSellerEvent",
      components: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 32,
      type: "struct Vec",
      components: [
        {
          name: "buf",
          type: 27,
          typeArguments: [
            {
              name: "",
              type: 13,
              typeArguments: null,
            },
          ],
        },
        {
          name: "len",
          type: 34,
          typeArguments: null,
        },
      ],
      typeParameters: [13],
    },
    {
      typeId: 33,
      type: "struct WithdrawnCollateralEvent",
      components: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 34,
      type: "u64",
      components: null,
      typeParameters: null,
    },
  ],
  functions: [
    {
      inputs: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      name: "accept_arbiter",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "arbiter",
          type: 17,
          typeArguments: null,
        },
        {
          name: "assets",
          type: 32,
          typeArguments: [
            {
              name: "",
              type: 18,
              typeArguments: null,
            },
          ],
        },
        {
          name: "buyer",
          type: 7,
          typeArguments: null,
        },
        {
          name: "deadline",
          type: 34,
          typeArguments: null,
        },
      ],
      name: "create_escrow",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
        {
          name: "payable",
          arguments: [],
        },
      ],
    },
    {
      inputs: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      name: "deposit",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
        {
          name: "payable",
          arguments: [],
        },
      ],
    },
    {
      inputs: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      name: "dispute",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "arbiter",
          type: 17,
          typeArguments: null,
        },
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      name: "propose_arbiter",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
        {
          name: "payable",
          arguments: [],
        },
      ],
    },
    {
      inputs: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
        {
          name: "payment_amount",
          type: 34,
          typeArguments: null,
        },
        {
          name: "user",
          type: 7,
          typeArguments: null,
        },
      ],
      name: "resolve_dispute",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      name: "return_deposit",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      name: "take_payment",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      name: "transfer_to_seller",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      name: "withdraw_collateral",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      name: "arbiter_proposal",
      output: {
        name: "",
        type: 8,
        typeArguments: [
          {
            name: "",
            type: 17,
            typeArguments: null,
          },
        ],
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      name: "assets",
      output: {
        name: "",
        type: 8,
        typeArguments: [
          {
            name: "",
            type: 18,
            typeArguments: null,
          },
        ],
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [],
      name: "escrow_count",
      output: {
        name: "",
        type: 34,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "identifier",
          type: 34,
          typeArguments: null,
        },
      ],
      name: "escrows",
      output: {
        name: "",
        type: 8,
        typeArguments: [
          {
            name: "",
            type: 24,
            typeArguments: null,
          },
        ],
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
  ],
  loggedTypes: [
    {
      logId: 0,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 1,
      loggedType: {
        name: "",
        type: 11,
        typeArguments: [],
      },
    },
    {
      logId: 2,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 3,
      loggedType: {
        name: "",
        type: 15,
        typeArguments: [],
      },
    },
    {
      logId: 4,
      loggedType: {
        name: "",
        type: 4,
        typeArguments: [],
      },
    },
    {
      logId: 5,
      loggedType: {
        name: "",
        type: 5,
        typeArguments: [],
      },
    },
    {
      logId: 6,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 7,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 8,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 9,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 10,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 11,
      loggedType: {
        name: "",
        type: 4,
        typeArguments: [],
      },
    },
    {
      logId: 12,
      loggedType: {
        name: "",
        type: 21,
        typeArguments: [],
      },
    },
    {
      logId: 13,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 14,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 15,
      loggedType: {
        name: "",
        type: 11,
        typeArguments: [],
      },
    },
    {
      logId: 16,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 17,
      loggedType: {
        name: "",
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 18,
      loggedType: {
        name: "",
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 19,
      loggedType: {
        name: "",
        type: 22,
        typeArguments: [],
      },
    },
    {
      logId: 20,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 21,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 22,
      loggedType: {
        name: "",
        type: 11,
        typeArguments: [],
      },
    },
    {
      logId: 23,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 24,
      loggedType: {
        name: "",
        type: 23,
        typeArguments: [],
      },
    },
    {
      logId: 25,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 26,
      loggedType: {
        name: "",
        type: 11,
        typeArguments: [],
      },
    },
    {
      logId: 27,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 28,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 29,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 30,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 31,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 32,
      loggedType: {
        name: "",
        type: 26,
        typeArguments: [],
      },
    },
    {
      logId: 33,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 34,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 35,
      loggedType: {
        name: "",
        type: 11,
        typeArguments: [],
      },
    },
    {
      logId: 36,
      loggedType: {
        name: "",
        type: 12,
        typeArguments: [],
      },
    },
    {
      logId: 37,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 38,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 39,
      loggedType: {
        name: "",
        type: 28,
        typeArguments: [],
      },
    },
    {
      logId: 40,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 41,
      loggedType: {
        name: "",
        type: 11,
        typeArguments: [],
      },
    },
    {
      logId: 42,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 43,
      loggedType: {
        name: "",
        type: 29,
        typeArguments: [],
      },
    },
    {
      logId: 44,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 45,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 46,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 47,
      loggedType: {
        name: "",
        type: 11,
        typeArguments: [],
      },
    },
    {
      logId: 48,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 49,
      loggedType: {
        name: "",
        type: 25,
        typeArguments: [],
      },
    },
    {
      logId: 50,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 51,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 52,
      loggedType: {
        name: "",
        type: 11,
        typeArguments: [],
      },
    },
    {
      logId: 53,
      loggedType: {
        name: "",
        type: 31,
        typeArguments: [],
      },
    },
    {
      logId: 54,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 55,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 56,
      loggedType: {
        name: "",
        type: 11,
        typeArguments: [],
      },
    },
    {
      logId: 57,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 58,
      loggedType: {
        name: "",
        type: 33,
        typeArguments: [],
      },
    },
  ],
  messagesTypes: [],
  configurables: [],
};

export class EscrowContractAbi__factory {
  static readonly abi = _abi;
  static createInterface(): EscrowContractAbiInterface {
    return new Interface(_abi) as unknown as EscrowContractAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    accountOrProvider: Account | Provider
  ): EscrowContractAbi {
    return new Contract(
      id,
      _abi,
      accountOrProvider
    ) as unknown as EscrowContractAbi;
  }
}
