[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "swap-exact-input"

[constants]
AMM_ID = { type = "b256", value = "0x7c1420f4d30178fdff677e7b718ab20fdf4c0dbca78d3b9602ee8cabe50349cb" }

[dependencies]
libraries = { path = "../../libraries" }
