[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "airdrop-distributor"

[dependencies]
# TODO: Update to master when https://github.com/FuelLabs/sway-libs/issues/6 is closed
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", branch = "bitzoic-6" }
