[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "airdrop-distributor"

[dependencies]
# TODO: Point to a release when https://github.com/FuelLabs/sway-libs/issues/16 is closed
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", branch = "master" }
