/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VaultAbi } from "./VaultAbi";

export { VaultAbi__factory } from "./factories/VaultAbi__factory";
