/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
} from "fuels";

interface VaultAbiInterface extends Interface {
  functions: {
    register_tokens: FunctionFragment;
    register_pool: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "register_tokens",
    values: [
      string,
      BigNumberish,
      [any, any, any, any, any, any, any, any],
      [any, any, any, any, any, any, any, any]
    ]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "register_pool",
    values: [string]
  ): Uint8Array;

  decodeFunctionData(
    functionFragment: "register_tokens",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "register_pool",
    data: BytesLike
  ): DecodedValue;
}

export class VaultAbi extends Contract {
  interface: VaultAbiInterface;
  functions: {
    register_tokens: InvokeFunction<
      [
        poolId: string,
        specialization: BigNumberish,
        tokens1: [any, any, any, any, any, any, any, any],
        assetManagers1: [any, any, any, any, any, any, any, any]
      ],
      void
    >;

    register_pool: InvokeFunction<[poolId: string], string>;
  };
}
