[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "exchange-contract"

[constants]
LIQUIDITY_MINER_FEE = { type = "u64", value = "333" }
MINIMUM_LIQUIDITY = { type = "u64", value = "100" }

[dependencies]
libraries = { path = "../../libraries" }
