/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, Wallet } from 'fuels';
import { Interface, Contract } from 'fuels';
import type { EscrowAbi, EscrowAbiInterface } from '../EscrowAbi';
const _abi = [
  {
    type: 'function',
    inputs: [
      {
        name: 'owner',
        type: 'enum Identity',
        components: [
          {
            name: 'Address',
            type: 'struct Address',
            components: [
              {
                name: 'value',
                type: 'b256',
                components: null,
              },
            ],
          },
          {
            name: 'ContractId',
            type: 'struct ContractId',
            components: [
              {
                name: 'value',
                type: 'b256',
                components: null,
              },
            ],
          },
        ],
      },
    ],
    name: 'constructor',
    outputs: [
      {
        name: '',
        type: '()',
        components: [],
      },
    ],
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'users',
        type: '[enum Identity; 2]',
        components: [
          {
            name: '__array_element',
            type: 'enum Identity',
            components: [
              {
                name: 'Address',
                type: 'struct Address',
                components: [
                  {
                    name: 'value',
                    type: 'b256',
                    components: null,
                  },
                ],
              },
              {
                name: 'ContractId',
                type: 'struct ContractId',
                components: [
                  {
                    name: 'value',
                    type: 'b256',
                    components: null,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        name: 'assets',
        type: '[struct Asset; 2]',
        components: [
          {
            name: '__array_element',
            type: 'struct Asset',
            components: [
              {
                name: 'amount',
                type: 'u64',
                components: null,
              },
              {
                name: 'id',
                type: 'struct ContractId',
                components: [
                  {
                    name: 'value',
                    type: 'b256',
                    components: null,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
    name: 'create_escrow',
    outputs: [
      {
        name: '',
        type: '()',
        components: [],
      },
    ],
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'identifier',
        type: 'u64',
        components: null,
      },
    ],
    name: 'deposit',
    outputs: [
      {
        name: '',
        type: '()',
        components: [],
      },
    ],
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'identifier',
        type: 'u64',
        components: null,
      },
    ],
    name: 'approve',
    outputs: [
      {
        name: '',
        type: '()',
        components: [],
      },
    ],
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'identifier',
        type: 'u64',
        components: null,
      },
    ],
    name: 'withdraw',
    outputs: [
      {
        name: '',
        type: '()',
        components: [],
      },
    ],
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'identifier',
        type: 'u64',
        components: null,
      },
      {
        name: 'user',
        type: 'enum Identity',
        components: [
          {
            name: 'Address',
            type: 'struct Address',
            components: [
              {
                name: 'value',
                type: 'b256',
                components: null,
              },
            ],
          },
          {
            name: 'ContractId',
            type: 'struct ContractId',
            components: [
              {
                name: 'value',
                type: 'b256',
                components: null,
              },
            ],
          },
        ],
      },
    ],
    name: 'user_data',
    outputs: [
      {
        name: '',
        type: 'struct User',
        components: [
          {
            name: 'approved',
            type: 'bool',
            components: null,
          },
          {
            name: 'asset',
            type: 'enum Option',
            components: [
              {
                name: 'Some',
                type: 'struct ContractId',
                components: [
                  {
                    name: 'value',
                    type: 'b256',
                    components: null,
                  },
                ],
              },
              {
                name: 'None',
                type: '()',
                components: [],
              },
            ],
          },
          {
            name: 'exists',
            type: 'bool',
            components: null,
          },
          {
            name: 'deposited',
            type: 'bool',
            components: null,
          },
        ],
      },
    ],
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'user',
        type: 'enum Identity',
        components: [
          {
            name: 'Address',
            type: 'struct Address',
            components: [
              {
                name: 'value',
                type: 'b256',
                components: null,
              },
            ],
          },
          {
            name: 'ContractId',
            type: 'struct ContractId',
            components: [
              {
                name: 'value',
                type: 'b256',
                components: null,
              },
            ],
          },
        ],
      },
    ],
    name: 'user_escrows',
    outputs: [
      {
        name: '',
        type: 'struct UserEscrows',
        components: [
          {
            name: 'active',
            type: '[u64; 1]',
            components: [
              {
                name: '__array_element',
                type: 'u64',
                components: null,
              },
            ],
          },
          {
            name: 'completed',
            type: '[u64; 1]',
            components: [
              {
                name: '__array_element',
                type: 'u64',
                components: null,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'identifier',
        type: 'u64',
        components: null,
      },
    ],
    name: 'escrow_data',
    outputs: [
      {
        name: '',
        type: 'struct EscrowData',
        components: [
          {
            name: 'approval_count',
            type: 'u64',
            components: null,
          },
          {
            name: 'assets',
            type: '[struct Asset; 2]',
            components: [
              {
                name: '__array_element',
                type: 'struct Asset',
                components: [
                  {
                    name: 'amount',
                    type: 'u64',
                    components: null,
                  },
                  {
                    name: 'id',
                    type: 'struct ContractId',
                    components: [
                      {
                        name: 'value',
                        type: 'b256',
                        components: null,
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            name: 'state',
            type: 'enum State',
            components: [
              {
                name: 'Pending',
                type: '()',
                components: [],
              },
              {
                name: 'Completed',
                type: '()',
                components: [],
              },
            ],
          },
          {
            name: 'threshold',
            type: 'u64',
            components: null,
          },
          {
            name: 'users',
            type: '[enum Identity; 2]',
            components: [
              {
                name: '__array_element',
                type: 'enum Identity',
                components: [
                  {
                    name: 'Address',
                    type: 'struct Address',
                    components: [
                      {
                        name: 'value',
                        type: 'b256',
                        components: null,
                      },
                    ],
                  },
                  {
                    name: 'ContractId',
                    type: 'struct ContractId',
                    components: [
                      {
                        name: 'value',
                        type: 'b256',
                        components: null,
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];

export class EscrowAbi__factory {
  static readonly abi = _abi;
  static createInterface(): EscrowAbiInterface {
    return new Interface(_abi) as EscrowAbiInterface;
  }
  static connect(id: string, walletOrProvider: Wallet | Provider): EscrowAbi {
    return new Contract(id, _abi, walletOrProvider) as EscrowAbi;
  }
}
