name: New Application Specification
description: "Designing a new application? Pick this template!"
title: "<title>"
labels: ["New Application"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Application Description
      description: Describe the application, motivation behind it and write a mini-specification
      placeholder: |
        #### Description
        The application ...

        #### Motivation
        It allows ...

        #### Specification
        ...
    validations:
      required: true
  - type: textarea
    id: features
    attributes:
      label: Features
      description: After you create this issue update the checklist below to track the progress of the sub tasks!
      placeholder: |
        - [ ] #(issue number 1)
        - [ ] #(issue number 2)
        - [ ] #(issue number 3)
    validations:
      required: true
