[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "token_contract"

[dependencies]
swayswap_abi = { path = "../swayswap_abi" }
token_abi = { path = "../token_abi" }
