/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, Wallet } from "fuels";
import { Interface, Contract } from "fuels";
import type {
  TodoContractAbi,
  TodoContractAbiInterface,
} from "../TodoContractAbi";
const _abi = [
  {
    type: "function",
    inputs: [
      {
        name: "index",
        type: "u8",
        components: null,
      },
      {
        name: "value",
        type: "str[20]",
        components: null,
      },
    ],
    name: "add_todo",
    outputs: [
      {
        name: "",
        type: "[struct Todo; 5]",
        components: [
          {
            name: "__array_element",
            type: "struct Todo",
            components: [
              {
                name: "completed",
                type: "bool",
                components: null,
              },
              {
                name: "value",
                type: "str[20]",
                components: null,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "index",
        type: "u8",
        components: null,
      },
    ],
    name: "toggle_todo",
    outputs: [
      {
        name: "",
        type: "[struct Todo; 5]",
        components: [
          {
            name: "__array_element",
            type: "struct Todo",
            components: [
              {
                name: "completed",
                type: "bool",
                components: null,
              },
              {
                name: "value",
                type: "str[20]",
                components: null,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "index",
        type: "u8",
        components: null,
      },
    ],
    name: "remove_todo",
    outputs: [
      {
        name: "",
        type: "[struct Todo; 5]",
        components: [
          {
            name: "__array_element",
            type: "struct Todo",
            components: [
              {
                name: "completed",
                type: "bool",
                components: null,
              },
              {
                name: "value",
                type: "str[20]",
                components: null,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    type: "function",
    inputs: [],
    name: "get_todos",
    outputs: [
      {
        name: "",
        type: "[struct Todo; 5]",
        components: [
          {
            name: "__array_element",
            type: "struct Todo",
            components: [
              {
                name: "completed",
                type: "bool",
                components: null,
              },
              {
                name: "value",
                type: "str[20]",
                components: null,
              },
            ],
          },
        ],
      },
    ],
  },
];

export class TodoContractAbi__factory {
  static readonly abi = _abi;
  static createInterface(): TodoContractAbiInterface {
    return new Interface(_abi) as TodoContractAbiInterface;
  }
  static connect(
    id: string,
    walletOrProvider: Wallet | Provider
  ): TodoContractAbi {
    return new Contract(id, _abi, walletOrProvider) as TodoContractAbi;
  }
}
