[project]
authors = ["Bikem"]
entry = "main.sw"
license = "Apache-2.0"
name = "swap_route"

[constants]
liquidity_miner_fee = { type = "u64", value = "333" }

[dependencies]
libraries = { path = "../../libraries" }
