[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "f-NFT-contract"

[dependencies]
src6 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.3.0" }
src20 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.3.0" }
