/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.76.2
  Forc version: 0.51.1
  Fuel-Core version: 0.22.1
*/

export type { TictactoeContractAbi } from './TictactoeContractAbi';

export { TictactoeContractAbi__factory } from './factories/TictactoeContractAbi__factory';
