/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.29.1
  Forc version: 0.32.2
  Fuel-Core version: 0.15.1
*/

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from 'fuels';

export type AddressInput = { value: string };
export type AddressOutput = AddressInput;

interface AssetAbiInterface extends Interface {
  functions: {
    mint_and_send_to_address: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: 'mint_and_send_to_address',
    values: [BigNumberish, AddressInput]
  ): Uint8Array;

  decodeFunctionData(functionFragment: 'mint_and_send_to_address', data: BytesLike): DecodedValue;
}

export class AssetAbi extends Contract {
  interface: AssetAbiInterface;
  functions: {
    mint_and_send_to_address: InvokeFunction<[amount: BigNumberish, recipient: AddressInput], void>;
  };
}
