[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "name-registry"

# This is the amount of units of the asset to charge per 100 seconds of registration duration for every name/entry
[constants]
price_per_hundred = { type = "u64", value = "1" }

[dependencies]
