/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.0
  Forc version: 0.60.0
  Fuel-Core version: 0.26.0
*/

export type { NFTContractAbi } from './NFTContractAbi';

export { NFTContractAbi__factory } from './factories/NFTContractAbi__factory';
