/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, BaseWalletLocked, AbstractAddress } from 'fuels';
import { Interface, Contract } from 'fuels';
import type { EnglishAuctionAbi, EnglishAuctionAbiInterface } from '../EnglishAuctionAbi';
const _abi = {
  types: [
    {
      typeId: 0,
      type: '()',
      components: [],
      typeParameters: null,
    },
    {
      typeId: 1,
      type: 'b256',
      components: null,
      typeParameters: null,
    },
    {
      typeId: 2,
      type: 'enum AccessError',
      components: [
        {
          name: 'AuctionIsNotClosed',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'AuctionIsNotOpen',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'NFTTransferNotApproved',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'SenderIsNotSeller',
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 3,
      type: 'enum AssetError',
      components: [
        {
          name: 'AssetsAreNotTheSame',
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 4,
      type: 'enum AuctionAsset',
      components: [
        {
          name: 'NFTAsset',
          type: 18,
          typeArguments: null,
        },
        {
          name: 'TokenAsset',
          type: 19,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 5,
      type: 'enum Identity',
      components: [
        {
          name: 'Address',
          type: 12,
          typeArguments: null,
        },
        {
          name: 'ContractId',
          type: 16,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 6,
      type: 'enum InitError',
      components: [
        {
          name: 'AuctionDurationNotProvided',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'BidAssetAmountNotZero',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'CannotAcceptMoreThanOneNFT',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'InitialPriceCannotBeZero',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'ReserveLessThanInitialPrice',
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 7,
      type: 'enum InputError',
      components: [
        {
          name: 'AuctionDoesNotExist',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'InitialPriceNotMet',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'IncorrectAmountProvided',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'IncorrectAssetProvided',
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 8,
      type: 'enum Option',
      components: [
        {
          name: 'None',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'Some',
          type: 11,
          typeArguments: null,
        },
      ],
      typeParameters: [11],
    },
    {
      typeId: 9,
      type: 'enum State',
      components: [
        {
          name: 'Closed',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'Open',
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 10,
      type: 'enum UserError',
      components: [
        {
          name: 'BidderIsSeller',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'UserHasAlreadyWithdrawn',
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 11,
      type: 'generic T',
      components: null,
      typeParameters: null,
    },
    {
      typeId: 12,
      type: 'struct Address',
      components: [
        {
          name: 'value',
          type: 1,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 13,
      type: 'struct Auction',
      components: [
        {
          name: 'bid_asset',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'end_block',
          type: 21,
          typeArguments: null,
        },
        {
          name: 'highest_bidder',
          type: 8,
          typeArguments: [
            {
              name: '',
              type: 5,
              typeArguments: null,
            },
          ],
        },
        {
          name: 'initial_price',
          type: 21,
          typeArguments: null,
        },
        {
          name: 'reserve_price',
          type: 8,
          typeArguments: [
            {
              name: '',
              type: 21,
              typeArguments: null,
            },
          ],
        },
        {
          name: 'sell_asset',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'seller',
          type: 5,
          typeArguments: null,
        },
        {
          name: 'state',
          type: 9,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 14,
      type: 'struct BidEvent',
      components: [
        {
          name: 'amount',
          type: 21,
          typeArguments: null,
        },
        {
          name: 'auction_id',
          type: 21,
          typeArguments: null,
        },
        {
          name: 'user',
          type: 5,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 15,
      type: 'struct CancelAuctionEvent',
      components: [
        {
          name: 'auction_id',
          type: 21,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 16,
      type: 'struct ContractId',
      components: [
        {
          name: 'value',
          type: 1,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 17,
      type: 'struct CreateAuctionEvent',
      components: [
        {
          name: 'auction_id',
          type: 21,
          typeArguments: null,
        },
        {
          name: 'bid_asset',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'sell_asset',
          type: 4,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 18,
      type: 'struct NFTAsset',
      components: [
        {
          name: 'asset_id',
          type: 16,
          typeArguments: null,
        },
        {
          name: 'token_id',
          type: 21,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 19,
      type: 'struct TokenAsset',
      components: [
        {
          name: 'amount',
          type: 21,
          typeArguments: null,
        },
        {
          name: 'asset_id',
          type: 16,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 20,
      type: 'struct WithdrawEvent',
      components: [
        {
          name: 'asset',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'auction_id',
          type: 21,
          typeArguments: null,
        },
        {
          name: 'user',
          type: 5,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 21,
      type: 'u64',
      components: null,
      typeParameters: null,
    },
  ],
  functions: [
    {
      inputs: [
        {
          name: 'auction_id',
          type: 21,
          typeArguments: null,
        },
      ],
      name: 'auction_info',
      output: {
        name: '',
        type: 8,
        typeArguments: [
          {
            name: '',
            type: 13,
            typeArguments: null,
          },
        ],
      },
    },
    {
      inputs: [
        {
          name: 'auction_id',
          type: 21,
          typeArguments: null,
        },
        {
          name: 'bid_asset',
          type: 4,
          typeArguments: null,
        },
      ],
      name: 'bid',
      output: {
        name: '',
        type: 0,
        typeArguments: null,
      },
    },
    {
      inputs: [
        {
          name: 'auction_id',
          type: 21,
          typeArguments: null,
        },
      ],
      name: 'cancel',
      output: {
        name: '',
        type: 0,
        typeArguments: null,
      },
    },
    {
      inputs: [
        {
          name: 'bid_asset',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'duration',
          type: 21,
          typeArguments: null,
        },
        {
          name: 'initial_price',
          type: 21,
          typeArguments: null,
        },
        {
          name: 'reserve_price',
          type: 8,
          typeArguments: [
            {
              name: '',
              type: 21,
              typeArguments: null,
            },
          ],
        },
        {
          name: 'seller',
          type: 5,
          typeArguments: null,
        },
        {
          name: 'sell_asset',
          type: 4,
          typeArguments: null,
        },
      ],
      name: 'create',
      output: {
        name: '',
        type: 21,
        typeArguments: null,
      },
    },
    {
      inputs: [
        {
          name: 'auction_id',
          type: 21,
          typeArguments: null,
        },
        {
          name: 'identity',
          type: 5,
          typeArguments: null,
        },
      ],
      name: 'deposit_balance',
      output: {
        name: '',
        type: 8,
        typeArguments: [
          {
            name: '',
            type: 4,
            typeArguments: null,
          },
        ],
      },
    },
    {
      inputs: [
        {
          name: 'auction_id',
          type: 21,
          typeArguments: null,
        },
      ],
      name: 'withdraw',
      output: {
        name: '',
        type: 0,
        typeArguments: null,
      },
    },
    {
      inputs: [],
      name: 'total_auctions',
      output: {
        name: '',
        type: 21,
        typeArguments: null,
      },
    },
  ],
  loggedTypes: [
    {
      logId: 312314,
      loggedType: {
        name: '',
        type: 7,
        typeArguments: [],
      },
    },
    {
      logId: 312486,
      loggedType: {
        name: '',
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 312966,
      loggedType: {
        name: '',
        type: 2,
        typeArguments: [],
      },
    },
    {
      logId: 313187,
      loggedType: {
        name: '',
        type: 7,
        typeArguments: [],
      },
    },
    {
      logId: 316194,
      loggedType: {
        name: '',
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 277692,
      loggedType: {
        name: '',
        type: 2,
        typeArguments: [],
      },
    },
    {
      logId: 317856,
      loggedType: {
        name: '',
        type: 7,
        typeArguments: [],
      },
    },
    {
      logId: 322342,
      loggedType: {
        name: '',
        type: 7,
        typeArguments: [],
      },
    },
    {
      logId: 326885,
      loggedType: {
        name: '',
        type: 7,
        typeArguments: [],
      },
    },
    {
      logId: 327770,
      loggedType: {
        name: '',
        type: 7,
        typeArguments: [],
      },
    },
    {
      logId: 317856,
      loggedType: {
        name: '',
        type: 7,
        typeArguments: [],
      },
    },
    {
      logId: 322342,
      loggedType: {
        name: '',
        type: 7,
        typeArguments: [],
      },
    },
    {
      logId: 326885,
      loggedType: {
        name: '',
        type: 7,
        typeArguments: [],
      },
    },
    {
      logId: 327770,
      loggedType: {
        name: '',
        type: 7,
        typeArguments: [],
      },
    },
    {
      logId: 333195,
      loggedType: {
        name: '',
        type: 7,
        typeArguments: [],
      },
    },
    {
      logId: 342472,
      loggedType: {
        name: '',
        type: 14,
        typeArguments: [],
      },
    },
    {
      logId: 347032,
      loggedType: {
        name: '',
        type: 7,
        typeArguments: [],
      },
    },
    {
      logId: 347168,
      loggedType: {
        name: '',
        type: 2,
        typeArguments: [],
      },
    },
    {
      logId: 347389,
      loggedType: {
        name: '',
        type: 2,
        typeArguments: [],
      },
    },
    {
      logId: 347997,
      loggedType: {
        name: '',
        type: 15,
        typeArguments: [],
      },
    },
    {
      logId: 348019,
      loggedType: {
        name: '',
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 348219,
      loggedType: {
        name: '',
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 348244,
      loggedType: {
        name: '',
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 349137,
      loggedType: {
        name: '',
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 349137,
      loggedType: {
        name: '',
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 349469,
      loggedType: {
        name: '',
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 349486,
      loggedType: {
        name: '',
        type: 7,
        typeArguments: [],
      },
    },
    {
      logId: 350370,
      loggedType: {
        name: '',
        type: 7,
        typeArguments: [],
      },
    },
    {
      logId: 351354,
      loggedType: {
        name: '',
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 277692,
      loggedType: {
        name: '',
        type: 2,
        typeArguments: [],
      },
    },
    {
      logId: 351354,
      loggedType: {
        name: '',
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 277692,
      loggedType: {
        name: '',
        type: 2,
        typeArguments: [],
      },
    },
    {
      logId: 351765,
      loggedType: {
        name: '',
        type: 17,
        typeArguments: [],
      },
    },
    {
      logId: 351950,
      loggedType: {
        name: '',
        type: 7,
        typeArguments: [],
      },
    },
    {
      logId: 352086,
      loggedType: {
        name: '',
        type: 2,
        typeArguments: [],
      },
    },
    {
      logId: 352727,
      loggedType: {
        name: '',
        type: 10,
        typeArguments: [],
      },
    },
    {
      logId: 277692,
      loggedType: {
        name: '',
        type: 2,
        typeArguments: [],
      },
    },
    {
      logId: 277692,
      loggedType: {
        name: '',
        type: 2,
        typeArguments: [],
      },
    },
    {
      logId: 277692,
      loggedType: {
        name: '',
        type: 2,
        typeArguments: [],
      },
    },
    {
      logId: 354628,
      loggedType: {
        name: '',
        type: 20,
        typeArguments: [],
      },
    },
  ],
};

export class EnglishAuctionAbi__factory {
  static readonly abi = _abi;
  static createInterface(): EnglishAuctionAbiInterface {
    return new Interface(_abi) as unknown as EnglishAuctionAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: BaseWalletLocked | Provider
  ): EnglishAuctionAbi {
    return new Contract(id, _abi, walletOrProvider) as unknown as EnglishAuctionAbi;
  }
}
