/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.30.0
  Forc version: 0.32.2
  Fuel-Core version: 0.15.1
*/

export type { MultisigContractAbi } from './MultisigContractAbi';

export { MultisigContractAbi__factory } from './factories/MultisigContractAbi__factory';
