/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.36.0
  Forc version: 0.35.3
  Fuel-Core version: 0.17.3
*/

export type { MultisigContractAbi } from './MultisigContractAbi';

export { MultisigContractAbi__factory } from './factories/MultisigContractAbi__factory';
