[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "swap-predicate"

[constants]
ASK_AMOUNT = { type = "u64", value = "42" }
# Change to an Address/ContractId types once https://github.com/FuelLabs/sway/issues/2647 is fixed
ASK_TOKEN_CONFIG = { type = "b256", value = "0x0101010101010101010101010101010101010101010101010101010101010101" }
RECEIVER_CONFIG = { type = "b256", value = "0x09c0b2d1a486c439a87bcba6b46a7a1a23f3897cc83a94521a96da5c23bc58db" }
