[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "native-asset-contract"

[dependencies]
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", branch = "bitzoic-bump-v0.52" }
standards = { git = "https://github.com/FuelLabs/sway-standards", branch = "bitzoic-bump-v0.52.1" }
