[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "NFT-contract"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.4.0" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.20.0" }
