/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, Wallet } from "fuels";
import { Interface, Contract } from "fuels";
import type { EscrowAbi, EscrowAbiInterface } from "../EscrowAbi";
const _abi = [
  {
    type: "function",
    inputs: [
      {
        name: "identifier",
        type: "u64",
        components: null,
        typeArguments: null,
      },
    ],
    name: "accept_arbiter",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "arbiter",
        type: "enum Identity",
        components: [
          {
            name: "Address",
            type: "struct Address",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "ContractId",
            type: "struct ContractId",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
    ],
    name: "arbiter_escrows",
    outputs: [
      {
        name: "",
        type: "[u64; 1]",
        components: [
          {
            name: "__array_element",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "buyer",
        type: "enum Identity",
        components: [
          {
            name: "Address",
            type: "struct Address",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "ContractId",
            type: "struct ContractId",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
    ],
    name: "buyer_escrows",
    outputs: [
      {
        name: "",
        type: "[u64; 1]",
        components: [
          {
            name: "__array_element",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "arbiter",
        type: "struct Arbiter",
        components: [
          {
            name: "address",
            type: "enum Identity",
            components: [
              {
                name: "Address",
                type: "struct Address",
                components: [
                  {
                    name: "value",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
              {
                name: "ContractId",
                type: "struct ContractId",
                components: [
                  {
                    name: "value",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "asset",
            type: "struct ContractId",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "fee_amount",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
      {
        name: "assets",
        type: "[struct Asset; 2]",
        components: [
          {
            name: "__array_element",
            type: "struct Asset",
            components: [
              {
                name: "amount",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "id",
                type: "struct ContractId",
                components: [
                  {
                    name: "value",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
      {
        name: "buyer",
        type: "enum Identity",
        components: [
          {
            name: "Address",
            type: "struct Address",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "ContractId",
            type: "struct ContractId",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
      {
        name: "deadline",
        type: "u64",
        components: null,
        typeArguments: null,
      },
    ],
    name: "create_escrow",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "identifier",
        type: "u64",
        components: null,
        typeArguments: null,
      },
    ],
    name: "deposit",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "identifier",
        type: "u64",
        components: null,
        typeArguments: null,
      },
    ],
    name: "dispute",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "arbiter",
        type: "struct Arbiter",
        components: [
          {
            name: "address",
            type: "enum Identity",
            components: [
              {
                name: "Address",
                type: "struct Address",
                components: [
                  {
                    name: "value",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
              {
                name: "ContractId",
                type: "struct ContractId",
                components: [
                  {
                    name: "value",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "asset",
            type: "struct ContractId",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "fee_amount",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
      {
        name: "identifier",
        type: "u64",
        components: null,
        typeArguments: null,
      },
    ],
    name: "propose_arbiter",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "identifier",
        type: "u64",
        components: null,
        typeArguments: null,
      },
      {
        name: "payment_amount",
        type: "u64",
        components: null,
        typeArguments: null,
      },
      {
        name: "user",
        type: "enum Identity",
        components: [
          {
            name: "Address",
            type: "struct Address",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "ContractId",
            type: "struct ContractId",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
    ],
    name: "resolve_dispute",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "identifier",
        type: "u64",
        components: null,
        typeArguments: null,
      },
    ],
    name: "return_deposit",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "seller",
        type: "enum Identity",
        components: [
          {
            name: "Address",
            type: "struct Address",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "ContractId",
            type: "struct ContractId",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
    ],
    name: "seller_escrows",
    outputs: [
      {
        name: "",
        type: "[u64; 1]",
        components: [
          {
            name: "__array_element",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "identifier",
        type: "u64",
        components: null,
        typeArguments: null,
      },
    ],
    name: "take_payment",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "identifier",
        type: "u64",
        components: null,
        typeArguments: null,
      },
    ],
    name: "transfer_to_seller",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "identifier",
        type: "u64",
        components: null,
        typeArguments: null,
      },
    ],
    name: "withdraw_collateral",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
];

export class EscrowAbi__factory {
  static readonly abi = _abi;
  static createInterface(): EscrowAbiInterface {
    return new Interface(_abi) as EscrowAbiInterface;
  }
  static connect(id: string, walletOrProvider: Wallet | Provider): EscrowAbi {
    return new Contract(id, _abi, walletOrProvider) as EscrowAbi;
  }
}
