/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.35.0
  Forc version: 0.35.3
  Fuel-Core version: 0.17.3
*/

export type { EscrowContractAbi } from "./EscrowContractAbi";

export { EscrowContractAbi__factory } from "./factories/EscrowContractAbi__factory";
