/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, Wallet } from "fuels";
import { Interface, Contract } from "fuels";
import type { VaultAbi, VaultAbiInterface } from "../VaultAbi";
const _abi = [
  {
    type: "function",
    inputs: [
      {
        name: "kind",
        type: "enum SwapKind",
        components: [
          {
            name: "GIVEN_IN",
            type: "()",
            components: [],
            typeArguments: null,
          },
          {
            name: "GIVEN_OUT",
            type: "()",
            components: [],
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
      {
        name: "swaps",
        type: "struct Vec",
        components: [
          {
            name: "buf",
            type: "struct RawVec",
            components: [
              {
                name: "ptr",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "cap",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "struct BatchSwapStep",
                components: [
                  {
                    name: "poolId",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                  {
                    name: "assetInIndex",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                  {
                    name: "assetOutIndex",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                  {
                    name: "amount",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                  {
                    name: "userData",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
            ],
          },
          {
            name: "len",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: [
          {
            name: "T",
            type: "struct BatchSwapStep",
            components: [
              {
                name: "poolId",
                type: "b256",
                components: null,
                typeArguments: null,
              },
              {
                name: "assetInIndex",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "assetOutIndex",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "amount",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "userData",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
        ],
      },
      {
        name: "assets",
        type: "struct Vec",
        components: [
          {
            name: "buf",
            type: "struct RawVec",
            components: [
              {
                name: "ptr",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "cap",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "struct ContractId",
                components: [
                  {
                    name: "value",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
            ],
          },
          {
            name: "len",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: [
          {
            name: "T",
            type: "struct ContractId",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
        ],
      },
      {
        name: "funds",
        type: "struct FundManagement",
        components: [
          {
            name: "sender",
            type: "struct Address",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "fromInternalBalance",
            type: "bool",
            components: null,
            typeArguments: null,
          },
          {
            name: "recipient",
            type: "struct Address",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "toInternalBalance",
            type: "bool",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
      {
        name: "limits",
        type: "struct Vec",
        components: [
          {
            name: "buf",
            type: "struct RawVec",
            components: [
              {
                name: "ptr",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "cap",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
          },
          {
            name: "len",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: [
          {
            name: "T",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
      },
      {
        name: "deadline",
        type: "u64",
        components: null,
        typeArguments: null,
      },
    ],
    name: "batch_swap",
    outputs: [
      {
        name: "",
        type: "struct Vec",
        components: [
          {
            name: "buf",
            type: "struct RawVec",
            components: [
              {
                name: "ptr",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "cap",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
          },
          {
            name: "len",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: [
          {
            name: "T",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "singleSwap",
        type: "struct SingleSwap",
        components: [
          {
            name: "poolId",
            type: "b256",
            components: null,
            typeArguments: null,
          },
          {
            name: "kind",
            type: "enum SwapKind",
            components: [
              {
                name: "GIVEN_IN",
                type: "()",
                components: [],
                typeArguments: null,
              },
              {
                name: "GIVEN_OUT",
                type: "()",
                components: [],
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "assetIn",
            type: "struct ContractId",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "assetOut",
            type: "struct ContractId",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "amount",
            type: "u64",
            components: null,
            typeArguments: null,
          },
          {
            name: "userData",
            type: "b256",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
      {
        name: "funds",
        type: "struct FundManagement",
        components: [
          {
            name: "sender",
            type: "struct Address",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "fromInternalBalance",
            type: "bool",
            components: null,
            typeArguments: null,
          },
          {
            name: "recipient",
            type: "struct Address",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "toInternalBalance",
            type: "bool",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
      {
        name: "limit",
        type: "u64",
        components: null,
        typeArguments: null,
      },
      {
        name: "deadline",
        type: "u64",
        components: null,
        typeArguments: null,
      },
    ],
    name: "swap",
    outputs: [
      {
        name: "",
        type: "u64",
        components: null,
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "kind",
        type: "enum SwapKind",
        components: [
          {
            name: "GIVEN_IN",
            type: "()",
            components: [],
            typeArguments: null,
          },
          {
            name: "GIVEN_OUT",
            type: "()",
            components: [],
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
      {
        name: "swaps",
        type: "struct Vec",
        components: [
          {
            name: "buf",
            type: "struct RawVec",
            components: [
              {
                name: "ptr",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "cap",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "struct BatchSwapStep",
                components: [
                  {
                    name: "poolId",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                  {
                    name: "assetInIndex",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                  {
                    name: "assetOutIndex",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                  {
                    name: "amount",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                  {
                    name: "userData",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
            ],
          },
          {
            name: "len",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: [
          {
            name: "T",
            type: "struct BatchSwapStep",
            components: [
              {
                name: "poolId",
                type: "b256",
                components: null,
                typeArguments: null,
              },
              {
                name: "assetInIndex",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "assetOutIndex",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "amount",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "userData",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
        ],
      },
      {
        name: "assets",
        type: "struct Vec",
        components: [
          {
            name: "buf",
            type: "struct RawVec",
            components: [
              {
                name: "ptr",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "cap",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "struct ContractId",
                components: [
                  {
                    name: "value",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
            ],
          },
          {
            name: "len",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: [
          {
            name: "T",
            type: "struct ContractId",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
        ],
      },
      {
        name: "funds",
        type: "struct FundManagement",
        components: [
          {
            name: "sender",
            type: "struct Address",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "fromInternalBalance",
            type: "bool",
            components: null,
            typeArguments: null,
          },
          {
            name: "recipient",
            type: "struct Address",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
          {
            name: "toInternalBalance",
            type: "bool",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
    ],
    name: "query_batch_swap",
    outputs: [
      {
        name: "",
        type: "struct Vec",
        components: [
          {
            name: "buf",
            type: "struct RawVec",
            components: [
              {
                name: "ptr",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "cap",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
          },
          {
            name: "len",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: [
          {
            name: "T",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "poolId",
        type: "b256",
        components: null,
        typeArguments: null,
      },
      {
        name: "tokens",
        type: "struct Vec",
        components: [
          {
            name: "buf",
            type: "struct RawVec",
            components: [
              {
                name: "ptr",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "cap",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "struct ContractId",
                components: [
                  {
                    name: "value",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
            ],
          },
          {
            name: "len",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: [
          {
            name: "T",
            type: "struct ContractId",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
        ],
      },
      {
        name: "assetManagers",
        type: "struct Vec",
        components: [
          {
            name: "buf",
            type: "struct RawVec",
            components: [
              {
                name: "ptr",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "cap",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "struct Address",
                components: [
                  {
                    name: "value",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
            ],
          },
          {
            name: "len",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: [
          {
            name: "T",
            type: "struct Address",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
        ],
      },
    ],
    name: "register_tokens",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "poolId",
        type: "b256",
        components: null,
        typeArguments: null,
      },
      {
        name: "tokens",
        type: "struct Vec",
        components: [
          {
            name: "buf",
            type: "struct RawVec",
            components: [
              {
                name: "ptr",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "cap",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "struct ContractId",
                components: [
                  {
                    name: "value",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
            ],
          },
          {
            name: "len",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: [
          {
            name: "T",
            type: "struct ContractId",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
        ],
      },
    ],
    name: "deregister_tokens",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "poolId",
        type: "b256",
        components: null,
        typeArguments: null,
      },
      {
        name: "sender",
        type: "struct Address",
        components: [
          {
            name: "value",
            type: "b256",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
      {
        name: "recipient",
        type: "struct Address",
        components: [
          {
            name: "value",
            type: "b256",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
      {
        name: "request",
        type: "struct JoinPoolRequest",
        components: [
          {
            name: "assets",
            type: "struct Vec",
            components: [
              {
                name: "buf",
                type: "struct RawVec",
                components: [
                  {
                    name: "ptr",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                  {
                    name: "cap",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: [
                  {
                    name: "T",
                    type: "struct ContractId",
                    components: [
                      {
                        name: "value",
                        type: "b256",
                        components: null,
                        typeArguments: null,
                      },
                    ],
                    typeArguments: null,
                  },
                ],
              },
              {
                name: "len",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "struct ContractId",
                components: [
                  {
                    name: "value",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
            ],
          },
          {
            name: "maxAmountsIn",
            type: "struct Vec",
            components: [
              {
                name: "buf",
                type: "struct RawVec",
                components: [
                  {
                    name: "ptr",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                  {
                    name: "cap",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: [
                  {
                    name: "T",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                ],
              },
              {
                name: "len",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
          },
          {
            name: "userData",
            type: "b256",
            components: null,
            typeArguments: null,
          },
          {
            name: "fromInternalBalance",
            type: "bool",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
    ],
    name: "join_pool",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "poolId",
        type: "b256",
        components: null,
        typeArguments: null,
      },
      {
        name: "sender",
        type: "struct Address",
        components: [
          {
            name: "value",
            type: "b256",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
      {
        name: "recipient",
        type: "struct Address",
        components: [
          {
            name: "value",
            type: "b256",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
      {
        name: "request",
        type: "struct ExitPoolRequest",
        components: [
          {
            name: "assets",
            type: "struct Vec",
            components: [
              {
                name: "buf",
                type: "struct RawVec",
                components: [
                  {
                    name: "ptr",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                  {
                    name: "cap",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: [
                  {
                    name: "T",
                    type: "struct ContractId",
                    components: [
                      {
                        name: "value",
                        type: "b256",
                        components: null,
                        typeArguments: null,
                      },
                    ],
                    typeArguments: null,
                  },
                ],
              },
              {
                name: "len",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "struct ContractId",
                components: [
                  {
                    name: "value",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
            ],
          },
          {
            name: "minAmountsOut",
            type: "struct Vec",
            components: [
              {
                name: "buf",
                type: "struct RawVec",
                components: [
                  {
                    name: "ptr",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                  {
                    name: "cap",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: [
                  {
                    name: "T",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                ],
              },
              {
                name: "len",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
          },
          {
            name: "userData",
            type: "b256",
            components: null,
            typeArguments: null,
          },
          {
            name: "toInternalBalance",
            type: "bool",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
    ],
    name: "exit_pool",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "recipient",
        type: "struct ContractId",
        components: [
          {
            name: "value",
            type: "b256",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
      {
        name: "tokens",
        type: "struct Vec",
        components: [
          {
            name: "buf",
            type: "struct RawVec",
            components: [
              {
                name: "ptr",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "cap",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "struct ContractId",
                components: [
                  {
                    name: "value",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
            ],
          },
          {
            name: "len",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: [
          {
            name: "T",
            type: "struct ContractId",
            components: [
              {
                name: "value",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
        ],
      },
      {
        name: "amounts",
        type: "struct Vec",
        components: [
          {
            name: "buf",
            type: "struct RawVec",
            components: [
              {
                name: "ptr",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "cap",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
          },
          {
            name: "len",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: [
          {
            name: "T",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
      },
      {
        name: "userData",
        type: "struct Vec",
        components: [
          {
            name: "buf",
            type: "struct RawVec",
            components: [
              {
                name: "ptr",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "cap",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "b256",
                components: null,
                typeArguments: null,
              },
            ],
          },
          {
            name: "len",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: [
          {
            name: "T",
            type: "b256",
            components: null,
            typeArguments: null,
          },
        ],
      },
    ],
    name: "flash_loan",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "ops",
        type: "struct Vec",
        components: [
          {
            name: "buf",
            type: "struct RawVec",
            components: [
              {
                name: "ptr",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "cap",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "struct PoolBalanceOp",
                components: [
                  {
                    name: "kind",
                    type: "enum PoolBalanceOpKind",
                    components: [
                      {
                        name: "WITHDRAW",
                        type: "()",
                        components: [],
                        typeArguments: null,
                      },
                      {
                        name: "DEPOSIT",
                        type: "()",
                        components: [],
                        typeArguments: null,
                      },
                      {
                        name: "UPDATE",
                        type: "()",
                        components: [],
                        typeArguments: null,
                      },
                    ],
                    typeArguments: null,
                  },
                  {
                    name: "poolId",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                  {
                    name: "token",
                    type: "struct ContractId",
                    components: [
                      {
                        name: "value",
                        type: "b256",
                        components: null,
                        typeArguments: null,
                      },
                    ],
                    typeArguments: null,
                  },
                  {
                    name: "amount",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
            ],
          },
          {
            name: "len",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: [
          {
            name: "T",
            type: "struct PoolBalanceOp",
            components: [
              {
                name: "kind",
                type: "enum PoolBalanceOpKind",
                components: [
                  {
                    name: "WITHDRAW",
                    type: "()",
                    components: [],
                    typeArguments: null,
                  },
                  {
                    name: "DEPOSIT",
                    type: "()",
                    components: [],
                    typeArguments: null,
                  },
                  {
                    name: "UPDATE",
                    type: "()",
                    components: [],
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
              {
                name: "poolId",
                type: "b256",
                components: null,
                typeArguments: null,
              },
              {
                name: "token",
                type: "struct ContractId",
                components: [
                  {
                    name: "value",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
              {
                name: "amount",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
        ],
      },
    ],
    name: "manage_pool_balance",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "ops",
        type: "struct Vec",
        components: [
          {
            name: "buf",
            type: "struct RawVec",
            components: [
              {
                name: "ptr",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "cap",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "struct UserBalanceOp",
                components: [
                  {
                    name: "amount",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                  {
                    name: "asset",
                    type: "struct ContractId",
                    components: [
                      {
                        name: "value",
                        type: "b256",
                        components: null,
                        typeArguments: null,
                      },
                    ],
                    typeArguments: null,
                  },
                  {
                    name: "kind",
                    type: "enum UserBalanceOpKind",
                    components: [
                      {
                        name: "DEPOSIT_INTERNAL",
                        type: "()",
                        components: [],
                        typeArguments: null,
                      },
                      {
                        name: "TRANSFER_EXTERNAL",
                        type: "()",
                        components: [],
                        typeArguments: null,
                      },
                      {
                        name: "TRANSFER_INTERNAL",
                        type: "()",
                        components: [],
                        typeArguments: null,
                      },
                      {
                        name: "WITHDRAW_INTERNAL",
                        type: "()",
                        components: [],
                        typeArguments: null,
                      },
                    ],
                    typeArguments: null,
                  },
                  {
                    name: "recipient",
                    type: "struct Address",
                    components: [
                      {
                        name: "value",
                        type: "b256",
                        components: null,
                        typeArguments: null,
                      },
                    ],
                    typeArguments: null,
                  },
                  {
                    name: "sender",
                    type: "struct Address",
                    components: [
                      {
                        name: "value",
                        type: "b256",
                        components: null,
                        typeArguments: null,
                      },
                    ],
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
            ],
          },
          {
            name: "len",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: [
          {
            name: "T",
            type: "struct UserBalanceOp",
            components: [
              {
                name: "amount",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "asset",
                type: "struct ContractId",
                components: [
                  {
                    name: "value",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
              {
                name: "kind",
                type: "enum UserBalanceOpKind",
                components: [
                  {
                    name: "DEPOSIT_INTERNAL",
                    type: "()",
                    components: [],
                    typeArguments: null,
                  },
                  {
                    name: "TRANSFER_EXTERNAL",
                    type: "()",
                    components: [],
                    typeArguments: null,
                  },
                  {
                    name: "TRANSFER_INTERNAL",
                    type: "()",
                    components: [],
                    typeArguments: null,
                  },
                  {
                    name: "WITHDRAW_INTERNAL",
                    type: "()",
                    components: [],
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
              {
                name: "recipient",
                type: "struct Address",
                components: [
                  {
                    name: "value",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
              {
                name: "sender",
                type: "struct Address",
                components: [
                  {
                    name: "value",
                    type: "b256",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: null,
              },
            ],
            typeArguments: null,
          },
        ],
      },
    ],
    name: "manage_user_balance",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "specialization",
        type: "enum PoolSpecialization",
        components: [
          {
            name: "GENERAL",
            type: "()",
            components: [],
            typeArguments: null,
          },
          {
            name: "MINIMAL_SWAP_INFO",
            type: "()",
            components: [],
            typeArguments: null,
          },
          {
            name: "TWO_TOKEN",
            type: "()",
            components: [],
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
    ],
    name: "register_pool",
    outputs: [
      {
        name: "",
        type: "b256",
        components: null,
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "newAuthorizer",
        type: "struct ContractId",
        components: [
          {
            name: "value",
            type: "b256",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
    ],
    name: "set_authorizer",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [
      {
        name: "sender",
        type: "struct Address",
        components: [
          {
            name: "value",
            type: "b256",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
      {
        name: "relayer",
        type: "struct Address",
        components: [
          {
            name: "value",
            type: "b256",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
      {
        name: "approved",
        type: "bool",
        components: null,
        typeArguments: null,
      },
    ],
    name: "set_relayer_approval",
    outputs: [
      {
        name: "",
        type: "()",
        components: [],
        typeArguments: null,
      },
    ],
  },
];

export class VaultAbi__factory {
  static readonly abi = _abi;
  static createInterface(): VaultAbiInterface {
    return new Interface(_abi) as VaultAbiInterface;
  }
  static connect(id: string, walletOrProvider: Wallet | Provider): VaultAbi {
    return new Contract(id, _abi, walletOrProvider) as VaultAbi;
  }
}
