/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from 'fuels';

export type AddressInput = { value: string };

export type AddressOutput = { value: string };

interface AssetAbiInterface extends Interface {
  functions: {
    mint_and_send_to_address: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: 'mint_and_send_to_address',
    values: [BigNumberish, AddressInput]
  ): Uint8Array;

  decodeFunctionData(functionFragment: 'mint_and_send_to_address', data: BytesLike): DecodedValue;
}

export class AssetAbi extends Contract {
  interface: AssetAbiInterface;
  functions: {
    mint_and_send_to_address: InvokeFunction<
      [amount: BigNumberish, recipient: AddressInput],
      boolean
    >;
  };
}
