/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  ContractCall,
  ContractCallOptions,
  Overrides,
  BigNumberish,
  BytesLike,
  CallResult,
  ScriptTransactionRequest,
  TransactionResult,
} from "fuels";

export type AddressInput = { value: string };

export type AddressOutput = { value: string };

export type ContractIdInput = { value: string };

export type ContractIdOutput = { value: string };

export type ArbiterInput = {
  address: IdentityInput;
  asset: ContractIdInput;
  fee_amount: BigNumberish;
};

export type ArbiterOutput = {
  address: IdentityOutput;
  asset: ContractIdOutput;
  fee_amount: bigint;
};

export type AssetInput = { amount: BigNumberish; id: ContractIdInput };

export type AssetOutput = { amount: bigint; id: ContractIdOutput };

export type IdentityInput = Partial<{
  Address: AddressInput;
  ContractId: ContractIdInput;
}>;

export type IdentityOutput = Partial<{
  Address: AddressOutput;
  ContractId: ContractIdOutput;
}>;

interface EscrowAbiInterface extends Interface {
  functions: {
    accept_arbiter: FunctionFragment;
    create_escrow: FunctionFragment;
    deposit: FunctionFragment;
    dispute: FunctionFragment;
    propose_arbiter: FunctionFragment;
    resolve_dispute: FunctionFragment;
    return_deposit: FunctionFragment;
    take_payment: FunctionFragment;
    transfer_to_seller: FunctionFragment;
    withdraw_collateral: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "accept_arbiter",
    values: [BigNumberish]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "create_escrow",
    values: [
      ArbiterInput,
      [AssetInput, AssetInput],
      IdentityInput,
      BigNumberish
    ]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "dispute",
    values: [BigNumberish]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "propose_arbiter",
    values: [ArbiterInput, BigNumberish]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "resolve_dispute",
    values: [BigNumberish, BigNumberish, IdentityInput]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "return_deposit",
    values: [BigNumberish]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "take_payment",
    values: [BigNumberish]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "transfer_to_seller",
    values: [BigNumberish]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "withdraw_collateral",
    values: [BigNumberish]
  ): Uint8Array;

  decodeFunctionData(
    functionFragment: "accept_arbiter",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "create_escrow",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "deposit",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "dispute",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "propose_arbiter",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "resolve_dispute",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "return_deposit",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "take_payment",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "transfer_to_seller",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "withdraw_collateral",
    data: BytesLike
  ): DecodedValue;
}

export class EscrowAbi extends Contract {
  interface: EscrowAbiInterface;
  prepareCall: {
    accept_arbiter(
      identifier: BigNumberish,
      options?: ContractCallOptions
    ): ContractCall;

    create_escrow(
      arbiter: ArbiterInput,
      assets: [AssetInput, AssetInput],
      buyer: IdentityInput,
      deadline: BigNumberish,
      options?: ContractCallOptions
    ): ContractCall;

    deposit(
      identifier: BigNumberish,
      options?: ContractCallOptions
    ): ContractCall;

    dispute(
      identifier: BigNumberish,
      options?: ContractCallOptions
    ): ContractCall;

    propose_arbiter(
      arbiter: ArbiterInput,
      identifier: BigNumberish,
      options?: ContractCallOptions
    ): ContractCall;

    resolve_dispute(
      identifier: BigNumberish,
      payment_amount: BigNumberish,
      user: IdentityInput,
      options?: ContractCallOptions
    ): ContractCall;

    return_deposit(
      identifier: BigNumberish,
      options?: ContractCallOptions
    ): ContractCall;

    take_payment(
      identifier: BigNumberish,
      options?: ContractCallOptions
    ): ContractCall;

    transfer_to_seller(
      identifier: BigNumberish,
      options?: ContractCallOptions
    ): ContractCall;

    withdraw_collateral(
      identifier: BigNumberish,
      options?: ContractCallOptions
    ): ContractCall;
  };
  submit: {
    accept_arbiter(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    create_escrow(
      arbiter: ArbiterInput,
      assets: [AssetInput, AssetInput],
      buyer: IdentityInput,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    deposit(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    dispute(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    propose_arbiter(
      arbiter: ArbiterInput,
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    resolve_dispute(
      identifier: BigNumberish,
      payment_amount: BigNumberish,
      user: IdentityInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    return_deposit(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    take_payment(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    transfer_to_seller(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    withdraw_collateral(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;
  };
  submitResult: {
    accept_arbiter(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;

    create_escrow(
      arbiter: ArbiterInput,
      assets: [AssetInput, AssetInput],
      buyer: IdentityInput,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;

    deposit(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;

    dispute(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;

    propose_arbiter(
      arbiter: ArbiterInput,
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;

    resolve_dispute(
      identifier: BigNumberish,
      payment_amount: BigNumberish,
      user: IdentityInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;

    return_deposit(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;

    take_payment(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;

    transfer_to_seller(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;

    withdraw_collateral(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;
  };
  dryRun: {
    accept_arbiter(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    create_escrow(
      arbiter: ArbiterInput,
      assets: [AssetInput, AssetInput],
      buyer: IdentityInput,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    deposit(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    dispute(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    propose_arbiter(
      arbiter: ArbiterInput,
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    resolve_dispute(
      identifier: BigNumberish,
      payment_amount: BigNumberish,
      user: IdentityInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    return_deposit(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    take_payment(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    transfer_to_seller(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    withdraw_collateral(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;
  };
  dryRunResult: {
    accept_arbiter(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    create_escrow(
      arbiter: ArbiterInput,
      assets: [AssetInput, AssetInput],
      buyer: IdentityInput,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    deposit(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    dispute(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    propose_arbiter(
      arbiter: ArbiterInput,
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    resolve_dispute(
      identifier: BigNumberish,
      payment_amount: BigNumberish,
      user: IdentityInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    return_deposit(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    take_payment(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    transfer_to_seller(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    withdraw_collateral(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;
  };
  simulate: {
    accept_arbiter(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    create_escrow(
      arbiter: ArbiterInput,
      assets: [AssetInput, AssetInput],
      buyer: IdentityInput,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    deposit(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    dispute(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    propose_arbiter(
      arbiter: ArbiterInput,
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    resolve_dispute(
      identifier: BigNumberish,
      payment_amount: BigNumberish,
      user: IdentityInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    return_deposit(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    take_payment(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    transfer_to_seller(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    withdraw_collateral(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;
  };
  simulateResult: {
    accept_arbiter(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    create_escrow(
      arbiter: ArbiterInput,
      assets: [AssetInput, AssetInput],
      buyer: IdentityInput,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    deposit(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    dispute(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    propose_arbiter(
      arbiter: ArbiterInput,
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    resolve_dispute(
      identifier: BigNumberish,
      payment_amount: BigNumberish,
      user: IdentityInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    return_deposit(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    take_payment(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    transfer_to_seller(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    withdraw_collateral(
      identifier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;
  };

  accept_arbiter(
    identifier: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<void>;

  create_escrow(
    arbiter: ArbiterInput,
    assets: [AssetInput, AssetInput],
    buyer: IdentityInput,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<void>;

  deposit(
    identifier: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<void>;

  dispute(
    identifier: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<void>;

  propose_arbiter(
    arbiter: ArbiterInput,
    identifier: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<void>;

  resolve_dispute(
    identifier: BigNumberish,
    payment_amount: BigNumberish,
    user: IdentityInput,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<void>;

  return_deposit(
    identifier: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<void>;

  take_payment(
    identifier: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<void>;

  transfer_to_seller(
    identifier: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<void>;

  withdraw_collateral(
    identifier: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<void>;
}
