[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "exchange"

[constants]
liquidity_miner_fee = { type = "u64", value = "333" }
minimum_liquidity = { type = "u64", value = "1" }

[dependencies]
libraries = { path = "../../libraries" }
