// mod balance_of;
mod earned;
// mod exit;
// mod get_reward;
// mod get_reward_for_duration;
// mod stake;
// mod last_time_reward_applicable;
// mod last_update_time;
// mod notify_reward_amount;
// mod owner;
// mod period_finish;
// mod recover_tokens;
// mod reward_per_token_paid;
// mod reward_per_token_stored;
// mod rewards;