[project]
name = "multisig-wallet"
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"

[dependencies]
std = { git = "https://github.com/FuelLabs/sway-lib-std", branch = "master" }
