/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  Overrides,
  BigNumberish,
  BytesLike,
  CallResult,
  ScriptTransactionRequest,
  TransactionResult,
} from 'fuels';

export type AddressInput = { value: string };

export type Address = { value: string };

interface AssetAbiInterface extends Interface {
  submit: {
    mint_and_send_to_address: FunctionFragment;
  };
  submitResult: {
    mint_and_send_to_address: FunctionFragment;
  };
  dryRun: {
    mint_and_send_to_address: FunctionFragment;
  };
  dryRunResult: {
    mint_and_send_to_address: FunctionFragment;
  };
  simulate: {
    mint_and_send_to_address: FunctionFragment;
  };
  simulateResult: {
    mint_and_send_to_address: FunctionFragment;
  };
  prepareCall: {
    mint_and_send_to_address: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: 'mint_and_send_to_address',
    values: [BigNumberish, AddressInput]
  ): Uint8Array;

  decodeFunctionData(functionFragment: 'mint_and_send_to_address', data: BytesLike): DecodedValue;
}

export class AssetAbi extends Contract {
  interface: AssetAbiInterface;
  submit: {
    mint_and_send_to_address(
      amount: BigNumberish,
      recipient: AddressInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<boolean>;
  };
  submitResult: {
    mint_and_send_to_address(
      amount: BigNumberish,
      recipient: AddressInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;
  };
  dryRun: {
    mint_and_send_to_address(
      amount: BigNumberish,
      recipient: AddressInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<boolean>;
  };
  dryRunResult: {
    mint_and_send_to_address(
      amount: BigNumberish,
      recipient: AddressInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;
  };
  prepareCall: {
    mint_and_send_to_address(
      amount: BigNumberish,
      recipient: AddressInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ScriptTransactionRequest>;
  };
  simulate: {
    mint_and_send_to_address(
      amount: BigNumberish,
      recipient: AddressInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<boolean>;
  };
  simulateResult: {
    mint_and_send_to_address(
      amount: BigNumberish,
      recipient: AddressInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;
  };

  mint_and_send_to_address(
    amount: BigNumberish,
    recipient: AddressInput,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<boolean>;
}
