name: github pages

on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  RUST_VERSION: 1.74.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.15"

      - run: mdbook build ./.docs/contributing-book

      - name: Deploy master
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.docs/contributing-book/book
          destination_dir: book
          cname: swayapps.fuel.network
        if: github.ref == 'refs/heads/master'
